--Create a Stored Procedure to display all users
Delimiter $$ create procedure sp_users() begin select user_id,name,age,gender,occupation,city,registration_date from users; end $$ Delimiter ;
--Create a procedure to display all transactions of a given user
Delimiter $$ create procedure sp_user_transaction(IN p_user_id int) begin select t.transaction_id,t.transaction_date,t.category,t.type,t.amount,t.payment_mode from accounts a join transactions t on a.account_id=t.account_id where a.user_id=p_user_id order by t.transaction_date; end $$ delimiter ;
--Create a procedure to calculate total income of a user
Delimiter $$ create procedure sp_total_income(IN p_user_id int) begin select u.user_id,u.name,sum(t.amount) as total_income from users u join accounts as a on u.user_id=a.user_id join transactions t on a.account_id=t.account_id where u.user_id=p_user_id and t.type='income'group by u.user_id,u.name; end $$ delimiter ;
--Create a procedure to calculate total expenses of a user
Delimiter $$ create procedure sp_total_expenses(in p_user_id int) begin select u.user_id,u.name,sum(t.amount) as total_expense from users u join accounts a on u.user_id=a.user_id join transactions t on a.account_id=t.account_id where u.user_id=p_user_id and t.type='expense' group by u.user_id,u.name; end $$ delimiter ;
--Create a procedure to calculate Savings of a user
Delimiter $$ create procedure sp_user_savings(IN p_user_id int) begin declare income decimal(15,2); declare expense decimal(15,2); select ifnull(sum(t.amount),0) into income from accounts a join transactions t on a.account_id=t.account_id where a.user_id=p_user_id and t.type='income'; select ifnull(sum(t.amount),0) into expense from accounts a join transactions t on a.account_id=t.account_id where a.user_id=p_user_id and t.type='expense'; select p_user_id as user_id,income,expense,(income-expense) as savings; end $$ delimiter ;
--Create a procedure to display the Financial Health Status of a user
Delimiter $$ create procedure sp_financial_health(IN p_user_id INT) begin declare income decimal(15,2); declare expense decimal(15,2); declare savings decimal(15,2); select ifnull(sum(t.amount),0) into income from accounts a join transactions t on a.account_id=t.account_id where a.user_id=p_user_id and t.type='income'; select ifnull(sum(t.amount),0) into expense from accounts a join transactions t on a.account_id=t.account_id where a.user_id=p_user_id and t.type='expense'; set savings=income-expense; if savings>=500000 then select 'Excellent financial status' as Status; elseif savings>=200000 then select 'Good financial status' as Status; elseif savings>=50000 then select 'Average financial status' as Status; else select 'Needs improvement' as Status; end if; end$$ delimiter ;
--Create a procedure to check whether a savings goal is completed
Delimiter $$ create procedure sp_goal_status(IN p_goal_id int) begin select goal_id,goal_name,current_amount,target_amount,case when current_amount>=target_amount then 'Completed' when current_amount>=target_amount*0.75 then 'Almost Completed' when current_amount>=target_amount*0.5 then 'Half Completed'else 'In progress' end as goal_status from savings_goals where goal_id=p_goal_id; end $$ delimiter ;
--Create a procedure to return the total account balance using an OUT parameter
Delimiter $$ create procedure sp_total_balance(IN p_user_id int,out total_balance decimal(15,2)) begin select ifnull(sum(current_balance),0) into total_balance from accounts a where a.user_id=p_user_id; end$$ delimiter ;
--Create a procedure using an INOUT parameter to update an investment amount
Delimiter $$ create procedure sp_update_investment(IN investmentId int,inout additional_amount decimal(15,2)) begin update investment set amount=amount+additional_amount where investment_id=investmentId; select amount into additional_amount from investment where investment_id=investmentId; end$$ delimiter ;
--Create a procedure to generate a complete Financial Summary Report
Delimiter $$ create procedure sp_financial_summary(IN p_user_id int) begin declare income decimal(15,2); declare expense decimal(15,2); declare investment decimal(15,2); declare savings decimal(15,2); select ifnull(sum(t.amount),0) into income from accounts a join transactions t on a.account_id=t.account_id where a.user_id=p_user_id and t.type='income'; select ifnull(sum(t.amount),0) into expense from accounts a join transactions t on a.account_id=t.account_id where a.user_id=p_user_id and t.type='expense'; select ifnull(sum(amount),0) into investment from investment where user_id=p_user_id; select ifnull(sum(current_amount),0) into savings from savings_goals where user_id=p_user_id; select income,expense,income-expense as net_savings,investment,savings; end $$ delimiter ;